import { describe, expect, test } from "bun:test";
import type { ProcessingActivity } from "./art30-register";
import {
  generateArt30Register,
  InvalidProcessingActivityError,
  validateProcessingActivity,
} from "./art30-register";

const SESSIONS_ACTIVITY: ProcessingActivity = {
  name: "Sessions collaborative events",
  product: "libre-ai/sessions",
  dataCategories: ["communication", "audit"],
  purposes: ["collaborative-work", "compliance-audit"],
  legalBasis: "contract",
  recipients: ["internal agents"],
  retentionRule: "sessions-content",
  dataSubjectType: "end-user",
  subjectRightsImplemented: ["access", "erasure"],
};

const CARRIERE_ACTIVITY: ProcessingActivity = {
  name: "Carriere lead tracking",
  product: "libre-ai/carriere",
  dataCategories: ["identity", "interaction"],
  purposes: ["job-search"],
  legalBasis: "consent",
  recipients: ["internal agents"],
  retentionRule: "carriere-leads",
  dataSubjectType: "lead",
  subjectRightsImplemented: ["access", "erasure", "portability"],
  transfersOutsideEU: { country: "CH", mechanism: "adequacy" },
  dpaAssessmentDate: "2026-07-23T00:00:00Z",
};

describe("validateProcessingActivity", () => {
  test("round-trips the Sessions fixture", () => {
    expect(validateProcessingActivity(SESSIONS_ACTIVITY)).toEqual(SESSIONS_ACTIVITY);
  });

  test("rejects malformed fields", () => {
    const bad: Record<string, unknown>[] = [
      { name: "" },
      { product: "" },
      { dataCategories: ["biometric"] },
      { dataCategories: [] },
      { purposes: [] },
      { legalBasis: "curiosity" },
      { retentionRule: "Not A Rule" },
      { dataSubjectType: "citizen" },
      { subjectRightsImplemented: ["deletion"] },
      { transfersOutsideEU: { country: "CH", mechanism: "handshake" } },
      { dpaAssessmentDate: "someday" },
    ];
    for (const override of bad) {
      expect(() => validateProcessingActivity({ ...SESSIONS_ACTIVITY, ...override })).toThrow(
        InvalidProcessingActivityError,
      );
    }
  });
});

describe("generateArt30Register", () => {
  test("renders deterministic markdown sorted by product then name", () => {
    const rendered = generateArt30Register([SESSIONS_ACTIVITY, CARRIERE_ACTIVITY]);
    expect(rendered).toBe(`# Record of processing activities (Art. 30 GDPR)

Generated by @libre-ai/rgpd-kit. One section per activity, sorted by product
then name. Each activity is declared and owned by its product inside its own
bounded context; this register aggregates declarations, never data.

## libre-ai/carriere — Carriere lead tracking

- **Purposes:** job-search
- **Legal basis:** consent
- **Data categories:** identity, interaction
- **Data subjects:** lead
- **Recipients:** internal agents
- **Retention rule:** carriere-leads
- **Subject rights implemented:** access, erasure, portability
- **Transfers outside EU:** CH (adequacy)
- **Last DPIA:** 2026-07-23T00:00:00Z

## libre-ai/sessions — Sessions collaborative events

- **Purposes:** collaborative-work, compliance-audit
- **Legal basis:** contract
- **Data categories:** communication, audit
- **Data subjects:** end-user
- **Recipients:** internal agents
- **Retention rule:** sessions-content
- **Subject rights implemented:** access, erasure
- **Transfers outside EU:** none
- **Last DPIA:** none
`);
  });

  test("validates every activity before rendering", () => {
    expect(() =>
      generateArt30Register([{ ...SESSIONS_ACTIVITY, legalBasis: "curiosity" } as never]),
    ).toThrow(InvalidProcessingActivityError);
  });
});
